name: nutritionapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-152.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  floor: ^1.4.2
  sqflite: ^2.3.0
  web_socket_channel: ^2.4.1
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  collection: ^1.18.0
  shared_preferences: ^2.2.2
  progress_dialog_null_safe: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2

flutter:
  uses-material-design: true
